/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BatalhaNaval;

import javax.swing.JButton;

/**
 *
 * @author 20161194010008
 */
public class BatalhaNaval extends javax.swing.JFrame {

    JButton[] button = new JButton[100];
    public BatalhaNaval() {
        initComponents();
        mar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton87 = new javax.swing.JButton();
        jButton88 = new javax.swing.JButton();
        jButton89 = new javax.swing.JButton();
        jButton90 = new javax.swing.JButton();
        jButton91 = new javax.swing.JButton();
        jButton92 = new javax.swing.JButton();
        jButton93 = new javax.swing.JButton();
        jButton94 = new javax.swing.JButton();
        jButton95 = new javax.swing.JButton();
        jButton96 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton97 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton98 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton99 = new javax.swing.JButton();
        jButton100 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jButton84 = new javax.swing.JButton();
        jButton85 = new javax.swing.JButton();
        jButton86 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jButton87, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 210, 60, 60));
        getContentPane().add(jButton88, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 474, 60, 60));
        getContentPane().add(jButton89, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 606, 60, 60));
        getContentPane().add(jButton90, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 540, 60, 60));
        getContentPane().add(jButton91, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 408, 60, 60));
        getContentPane().add(jButton92, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 474, 60, 60));
        getContentPane().add(jButton93, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 342, 60, 60));
        getContentPane().add(jButton94, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 540, 60, 60));
        getContentPane().add(jButton95, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 342, 60, 60));
        getContentPane().add(jButton96, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 408, 60, 60));
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 210, 60, 60));
        getContentPane().add(jButton97, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 78, 60, 60));
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 276, 60, 60));
        getContentPane().add(jButton98, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 606, 60, 60));
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 342, 60, 60));
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 408, 60, 60));
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 474, 60, 60));
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 540, 60, 60));
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 342, 60, 60));

        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 408, 60, 60));
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 606, 60, 60));
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 78, 60, 60));
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 12, 60, 60));
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 78, 60, 60));
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 146, 60, 60));
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 12, 60, 60));
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 78, 60, 60));
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 144, 60, 60));
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 212, 60, 60));
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 278, 60, 60));
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 144, 60, 60));
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 12, 60, 60));
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 60, 60));
        getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 606, 60, 60));
        getContentPane().add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 474, 60, 60));
        getContentPane().add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 210, 60, 60));
        getContentPane().add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 12, 60, 60));
        getContentPane().add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 78, 60, 60));
        getContentPane().add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 276, 60, 60));
        getContentPane().add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 144, 60, 60));
        getContentPane().add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 276, 60, 60));
        getContentPane().add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 210, 60, 60));
        getContentPane().add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 474, 60, 60));
        getContentPane().add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 606, 60, 60));
        getContentPane().add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 540, 60, 60));
        getContentPane().add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 408, 60, 60));
        getContentPane().add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 474, 60, 60));
        getContentPane().add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 342, 60, 60));
        getContentPane().add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 540, 60, 60));
        getContentPane().add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 342, 60, 60));
        getContentPane().add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 408, 60, 60));
        getContentPane().add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 606, 60, 60));
        getContentPane().add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 210, 60, 60));
        getContentPane().add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 144, 60, 60));
        getContentPane().add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 276, 60, 60));
        getContentPane().add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 276, 60, 60));
        getContentPane().add(jButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 342, 60, 60));
        getContentPane().add(jButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 210, 60, 60));
        getContentPane().add(jButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 408, 60, 60));
        getContentPane().add(jButton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 474, 60, 60));
        getContentPane().add(jButton49, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 474, 60, 60));
        getContentPane().add(jButton50, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 606, 60, 60));
        getContentPane().add(jButton51, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 540, 60, 60));
        getContentPane().add(jButton52, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 540, 60, 60));
        getContentPane().add(jButton53, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 342, 60, 60));
        getContentPane().add(jButton54, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 408, 60, 60));
        getContentPane().add(jButton55, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 408, 60, 60));
        getContentPane().add(jButton56, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 474, 60, 60));
        getContentPane().add(jButton57, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 342, 60, 60));
        getContentPane().add(jButton58, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, 60, 60));
        getContentPane().add(jButton59, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 606, 60, 60));
        getContentPane().add(jButton60, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 342, 60, 60));
        getContentPane().add(jButton61, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 408, 60, 60));
        getContentPane().add(jButton62, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 78, 60, 60));
        getContentPane().add(jButton63, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 606, 60, 60));
        getContentPane().add(jButton64, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 144, 60, 60));

        jButton65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton65ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton65, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 12, 60, 60));
        getContentPane().add(jButton66, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 12, 60, 60));
        getContentPane().add(jButton67, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 78, 60, 60));
        getContentPane().add(jButton68, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 540, 60, 60));
        getContentPane().add(jButton69, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 146, 60, 60));
        getContentPane().add(jButton70, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 606, 60, 60));
        getContentPane().add(jButton71, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 12, 60, 60));
        getContentPane().add(jButton72, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 474, 60, 60));
        getContentPane().add(jButton73, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 78, 60, 60));
        getContentPane().add(jButton74, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 144, 60, 60));
        getContentPane().add(jButton75, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 60, 60));
        getContentPane().add(jButton76, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 12, 60, 60));
        getContentPane().add(jButton77, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 212, 60, 60));
        getContentPane().add(jButton78, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 78, 60, 60));
        getContentPane().add(jButton99, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 144, 60, 60));
        getContentPane().add(jButton100, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 12, 60, 60));
        getContentPane().add(jButton79, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 278, 60, 60));
        getContentPane().add(jButton80, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 276, 60, 60));
        getContentPane().add(jButton81, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 210, 60, 60));
        getContentPane().add(jButton82, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 12, 60, 60));
        getContentPane().add(jButton83, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 78, 60, 60));
        getContentPane().add(jButton84, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 276, 60, 60));
        getContentPane().add(jButton85, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 144, 60, 60));
        getContentPane().add(jButton86, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 276, 60, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton65ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton65ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BatalhaNaval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BatalhaNaval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BatalhaNaval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BatalhaNaval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BatalhaNaval().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton100;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton85;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton87;
    private javax.swing.JButton jButton88;
    private javax.swing.JButton jButton89;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton90;
    private javax.swing.JButton jButton91;
    private javax.swing.JButton jButton92;
    private javax.swing.JButton jButton93;
    private javax.swing.JButton jButton94;
    private javax.swing.JButton jButton95;
    private javax.swing.JButton jButton96;
    private javax.swing.JButton jButton97;
    private javax.swing.JButton jButton98;
    private javax.swing.JButton jButton99;
    // End of variables declaration//GEN-END:variables

    private void mar() {
        
        button[0] = jButton1;
        
        
        desespero();
       
    }

    private void desespero() {
        for(int e = 0; e != 100; e++){
            button[e].setIcon(new javax.swing.ImageIcon(getClass().getResource("/BatalhaNaval/imagens/marP.jpg")));
        }
    }
}
